# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(556, 330)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(120, 50, 31, 21))
        self.label.setObjectName("label")
        self.variety = QtWidgets.QComboBox(parent=Dialog)
        self.variety.setGeometry(QtCore.QRect(170, 50, 291, 22))
        self.variety.setObjectName("variety")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 90, 91, 21))
        self.label_2.setObjectName("label_2")
        self.roast = QtWidgets.QComboBox(parent=Dialog)
        self.roast.setGeometry(QtCore.QRect(170, 90, 291, 22))
        self.roast.setObjectName("roast")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 130, 101, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(70, 170, 81, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(110, 210, 31, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=Dialog)
        self.label_6.setGeometry(QtCore.QRect(80, 240, 81, 31))
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(170, 130, 291, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.taste = QtWidgets.QLineEdit(parent=Dialog)
        self.taste.setGeometry(QtCore.QRect(170, 170, 291, 20))
        self.taste.setObjectName("taste")
        self.price = QtWidgets.QLineEdit(parent=Dialog)
        self.price.setGeometry(QtCore.QRect(170, 210, 291, 20))
        self.price.setObjectName("price")
        self.volume = QtWidgets.QLineEdit(parent=Dialog)
        self.volume.setGeometry(QtCore.QRect(170, 250, 291, 20))
        self.volume.setObjectName("volume")
        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton.setGeometry(QtCore.QRect(190, 280, 171, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "сорт"))
        self.label_2.setText(_translate("Dialog", "степень обжарки"))
        self.label_3.setText(_translate("Dialog", "молотый/в зернах"))
        self.label_4.setText(_translate("Dialog", "описание вкуса"))
        self.label_5.setText(_translate("Dialog", "цена"))
        self.label_6.setText(_translate("Dialog", "объем упаковки"))
        self.pushButton.setText(_translate("Dialog", "Применить"))
